// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OauthAccountsColumns holds the columns for the "oauth_accounts" table.
	OauthAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_user_id", Type: field.TypeString},
		{Name: "access_token", Type: field.TypeString, Nullable: true},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true},
		{Name: "token_expiry", Type: field.TypeTime, Nullable: true},
		{Name: "user_oauth_accounts", Type: field.TypeUUID, Nullable: true},
	}
	// OauthAccountsTable holds the schema information for the "oauth_accounts" table.
	OauthAccountsTable = &schema.Table{
		Name:       "oauth_accounts",
		Columns:    OauthAccountsColumns,
		PrimaryKey: []*schema.Column{OauthAccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "oauth_accounts_users_oauth_accounts",
				Columns:    []*schema.Column{OauthAccountsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "show_id", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "password", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "salt", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OauthAccountsTable,
		UsersTable,
	}
)

func init() {
	OauthAccountsTable.ForeignKeys[0].RefTable = UsersTable
}
