// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"com.goa/ent/oauthaccount"
	"com.goa/ent/predicate"
	"com.goa/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OAuthAccountQuery is the builder for querying OAuthAccount entities.
type OAuthAccountQuery struct {
	config
	ctx        *QueryContext
	order      []oauthaccount.OrderOption
	inters     []Interceptor
	predicates []predicate.OAuthAccount
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OAuthAccountQuery builder.
func (oaq *OAuthAccountQuery) Where(ps ...predicate.OAuthAccount) *OAuthAccountQuery {
	oaq.predicates = append(oaq.predicates, ps...)
	return oaq
}

// Limit the number of records to be returned by this query.
func (oaq *OAuthAccountQuery) Limit(limit int) *OAuthAccountQuery {
	oaq.ctx.Limit = &limit
	return oaq
}

// Offset to start from.
func (oaq *OAuthAccountQuery) Offset(offset int) *OAuthAccountQuery {
	oaq.ctx.Offset = &offset
	return oaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oaq *OAuthAccountQuery) Unique(unique bool) *OAuthAccountQuery {
	oaq.ctx.Unique = &unique
	return oaq
}

// Order specifies how the records should be ordered.
func (oaq *OAuthAccountQuery) Order(o ...oauthaccount.OrderOption) *OAuthAccountQuery {
	oaq.order = append(oaq.order, o...)
	return oaq
}

// QueryUser chains the current query on the "user" edge.
func (oaq *OAuthAccountQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: oaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthaccount.Table, oauthaccount.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, oauthaccount.UserTable, oauthaccount.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(oaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OAuthAccount entity from the query.
// Returns a *NotFoundError when no OAuthAccount was found.
func (oaq *OAuthAccountQuery) First(ctx context.Context) (*OAuthAccount, error) {
	nodes, err := oaq.Limit(1).All(setContextOp(ctx, oaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oauthaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oaq *OAuthAccountQuery) FirstX(ctx context.Context) *OAuthAccount {
	node, err := oaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OAuthAccount ID from the query.
// Returns a *NotFoundError when no OAuthAccount ID was found.
func (oaq *OAuthAccountQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oaq.Limit(1).IDs(setContextOp(ctx, oaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oauthaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oaq *OAuthAccountQuery) FirstIDX(ctx context.Context) int {
	id, err := oaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OAuthAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OAuthAccount entity is found.
// Returns a *NotFoundError when no OAuthAccount entities are found.
func (oaq *OAuthAccountQuery) Only(ctx context.Context) (*OAuthAccount, error) {
	nodes, err := oaq.Limit(2).All(setContextOp(ctx, oaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oauthaccount.Label}
	default:
		return nil, &NotSingularError{oauthaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oaq *OAuthAccountQuery) OnlyX(ctx context.Context) *OAuthAccount {
	node, err := oaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OAuthAccount ID in the query.
// Returns a *NotSingularError when more than one OAuthAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (oaq *OAuthAccountQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oaq.Limit(2).IDs(setContextOp(ctx, oaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oauthaccount.Label}
	default:
		err = &NotSingularError{oauthaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oaq *OAuthAccountQuery) OnlyIDX(ctx context.Context) int {
	id, err := oaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OAuthAccounts.
func (oaq *OAuthAccountQuery) All(ctx context.Context) ([]*OAuthAccount, error) {
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryAll)
	if err := oaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OAuthAccount, *OAuthAccountQuery]()
	return withInterceptors[[]*OAuthAccount](ctx, oaq, qr, oaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oaq *OAuthAccountQuery) AllX(ctx context.Context) []*OAuthAccount {
	nodes, err := oaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OAuthAccount IDs.
func (oaq *OAuthAccountQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oaq.ctx.Unique == nil && oaq.path != nil {
		oaq.Unique(true)
	}
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryIDs)
	if err = oaq.Select(oauthaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oaq *OAuthAccountQuery) IDsX(ctx context.Context) []int {
	ids, err := oaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oaq *OAuthAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryCount)
	if err := oaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oaq, querierCount[*OAuthAccountQuery](), oaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oaq *OAuthAccountQuery) CountX(ctx context.Context) int {
	count, err := oaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oaq *OAuthAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oaq.ctx, ent.OpQueryExist)
	switch _, err := oaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oaq *OAuthAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := oaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OAuthAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oaq *OAuthAccountQuery) Clone() *OAuthAccountQuery {
	if oaq == nil {
		return nil
	}
	return &OAuthAccountQuery{
		config:     oaq.config,
		ctx:        oaq.ctx.Clone(),
		order:      append([]oauthaccount.OrderOption{}, oaq.order...),
		inters:     append([]Interceptor{}, oaq.inters...),
		predicates: append([]predicate.OAuthAccount{}, oaq.predicates...),
		withUser:   oaq.withUser.Clone(),
		// clone intermediate query.
		sql:  oaq.sql.Clone(),
		path: oaq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (oaq *OAuthAccountQuery) WithUser(opts ...func(*UserQuery)) *OAuthAccountQuery {
	query := (&UserClient{config: oaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oaq.withUser = query
	return oaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Provider string `json:"provider,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OAuthAccount.Query().
//		GroupBy(oauthaccount.FieldProvider).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oaq *OAuthAccountQuery) GroupBy(field string, fields ...string) *OAuthAccountGroupBy {
	oaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OAuthAccountGroupBy{build: oaq}
	grbuild.flds = &oaq.ctx.Fields
	grbuild.label = oauthaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Provider string `json:"provider,omitempty"`
//	}
//
//	client.OAuthAccount.Query().
//		Select(oauthaccount.FieldProvider).
//		Scan(ctx, &v)
func (oaq *OAuthAccountQuery) Select(fields ...string) *OAuthAccountSelect {
	oaq.ctx.Fields = append(oaq.ctx.Fields, fields...)
	sbuild := &OAuthAccountSelect{OAuthAccountQuery: oaq}
	sbuild.label = oauthaccount.Label
	sbuild.flds, sbuild.scan = &oaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OAuthAccountSelect configured with the given aggregations.
func (oaq *OAuthAccountQuery) Aggregate(fns ...AggregateFunc) *OAuthAccountSelect {
	return oaq.Select().Aggregate(fns...)
}

func (oaq *OAuthAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oaq); err != nil {
				return err
			}
		}
	}
	for _, f := range oaq.ctx.Fields {
		if !oauthaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oaq.path != nil {
		prev, err := oaq.path(ctx)
		if err != nil {
			return err
		}
		oaq.sql = prev
	}
	return nil
}

func (oaq *OAuthAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OAuthAccount, error) {
	var (
		nodes       = []*OAuthAccount{}
		withFKs     = oaq.withFKs
		_spec       = oaq.querySpec()
		loadedTypes = [1]bool{
			oaq.withUser != nil,
		}
	)
	if oaq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OAuthAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OAuthAccount{config: oaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oaq.withUser; query != nil {
		if err := oaq.loadUser(ctx, query, nodes, nil,
			func(n *OAuthAccount, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oaq *OAuthAccountQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*OAuthAccount, init func(*OAuthAccount), assign func(*OAuthAccount, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OAuthAccount)
	for i := range nodes {
		if nodes[i].user_oauth_accounts == nil {
			continue
		}
		fk := *nodes[i].user_oauth_accounts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_oauth_accounts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (oaq *OAuthAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oaq.querySpec()
	_spec.Node.Columns = oaq.ctx.Fields
	if len(oaq.ctx.Fields) > 0 {
		_spec.Unique = oaq.ctx.Unique != nil && *oaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oaq.driver, _spec)
}

func (oaq *OAuthAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(oauthaccount.Table, oauthaccount.Columns, sqlgraph.NewFieldSpec(oauthaccount.FieldID, field.TypeInt))
	_spec.From = oaq.sql
	if unique := oaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oaq.path != nil {
		_spec.Unique = true
	}
	if fields := oaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccount.FieldID)
		for i := range fields {
			if fields[i] != oauthaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oaq *OAuthAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oaq.driver.Dialect())
	t1 := builder.Table(oauthaccount.Table)
	columns := oaq.ctx.Fields
	if len(columns) == 0 {
		columns = oauthaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oaq.sql != nil {
		selector = oaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oaq.ctx.Unique != nil && *oaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oaq.predicates {
		p(selector)
	}
	for _, p := range oaq.order {
		p(selector)
	}
	if offset := oaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OAuthAccountGroupBy is the group-by builder for OAuthAccount entities.
type OAuthAccountGroupBy struct {
	selector
	build *OAuthAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oagb *OAuthAccountGroupBy) Aggregate(fns ...AggregateFunc) *OAuthAccountGroupBy {
	oagb.fns = append(oagb.fns, fns...)
	return oagb
}

// Scan applies the selector query and scans the result into the given value.
func (oagb *OAuthAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oagb.build.ctx, ent.OpQueryGroupBy)
	if err := oagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthAccountQuery, *OAuthAccountGroupBy](ctx, oagb.build, oagb, oagb.build.inters, v)
}

func (oagb *OAuthAccountGroupBy) sqlScan(ctx context.Context, root *OAuthAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oagb.fns))
	for _, fn := range oagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oagb.flds)+len(oagb.fns))
		for _, f := range *oagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OAuthAccountSelect is the builder for selecting fields of OAuthAccount entities.
type OAuthAccountSelect struct {
	*OAuthAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oas *OAuthAccountSelect) Aggregate(fns ...AggregateFunc) *OAuthAccountSelect {
	oas.fns = append(oas.fns, fns...)
	return oas
}

// Scan applies the selector query and scans the result into the given value.
func (oas *OAuthAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oas.ctx, ent.OpQuerySelect)
	if err := oas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthAccountQuery, *OAuthAccountSelect](ctx, oas.OAuthAccountQuery, oas, oas.inters, v)
}

func (oas *OAuthAccountSelect) sqlScan(ctx context.Context, root *OAuthAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oas.fns))
	for _, fn := range oas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
