// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"com.goa/ent/oauthaccount"
	"com.goa/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthAccountDelete is the builder for deleting a OAuthAccount entity.
type OAuthAccountDelete struct {
	config
	hooks    []Hook
	mutation *OAuthAccountMutation
}

// Where appends a list predicates to the OAuthAccountDelete builder.
func (oad *OAuthAccountDelete) Where(ps ...predicate.OAuthAccount) *OAuthAccountDelete {
	oad.mutation.Where(ps...)
	return oad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oad *OAuthAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, oad.sqlExec, oad.mutation, oad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oad *OAuthAccountDelete) ExecX(ctx context.Context) int {
	n, err := oad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oad *OAuthAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthaccount.Table, sqlgraph.NewFieldSpec(oauthaccount.FieldID, field.TypeInt))
	if ps := oad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oad.mutation.done = true
	return affected, err
}

// OAuthAccountDeleteOne is the builder for deleting a single OAuthAccount entity.
type OAuthAccountDeleteOne struct {
	oad *OAuthAccountDelete
}

// Where appends a list predicates to the OAuthAccountDelete builder.
func (oado *OAuthAccountDeleteOne) Where(ps ...predicate.OAuthAccount) *OAuthAccountDeleteOne {
	oado.oad.mutation.Where(ps...)
	return oado
}

// Exec executes the deletion query.
func (oado *OAuthAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := oado.oad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oado *OAuthAccountDeleteOne) ExecX(ctx context.Context) {
	if err := oado.Exec(ctx); err != nil {
		panic(err)
	}
}
