// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuthAccount is the predicate function for oauthaccount builders.
type OAuthAccount func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
